# Generated by Django 2.1.7 on 2019-02-23 14:44

import datetime
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_num', models.IntegerField(default=1, verbose_name='已选商品数量')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name_plural': '购物车表',
                'db_table': 'tbl_cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cg_name', models.CharField(max_length=20, verbose_name='大类名字')),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('rem_order', models.IntegerField(default=0, verbose_name='推荐等级')),
            ],
            options={
                'verbose_name_plural': '商品大类表',
                'db_table': 'tbl_category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField(max_length=200, verbose_name='评论内容')),
            ],
            options={
                'verbose_name_plural': '商品评论表',
                'db_table': 'tbl_comment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('pay_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付方式')),
                ('is_pay', models.BooleanField(default=False, verbose_name='是否已支付')),
                ('order_price', models.FloatField(default=0, verbose_name='订单总价')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name_plural': '订单表',
                'db_table': 'tbl_order',
            },
        ),
        migrations.CreateModel(
            name='Prod_collect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': '产品收藏表',
                'db_table': 'tbl_prod_collect',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=20, verbose_name='商品名字')),
                ('prod_longname', models.TextField(max_length=100, verbose_name='商品长名字')),
                ('prod_img', models.ImageField(upload_to=shop.models.upload_to, verbose_name='商品图片')),
                ('prod_rollimg1', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='商品轮播图')),
                ('prod_rollimg2', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='商品轮播图2')),
                ('prod_rollimg3', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='商品轮播图3')),
                ('prod_rollimg4', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='商品轮播图4')),
                ('prod_desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='商品描述')),
                ('prod_price', models.FloatField(verbose_name='单价')),
                ('prod_num', models.IntegerField(default=0, verbose_name='库存')),
                ('prod_brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='商品品牌')),
                ('prod_sales', models.IntegerField(default=0, verbose_name='总销量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name_plural': '商品表',
                'db_table': 'tbl_product',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=shop.models.upload_to, verbose_name='首页滚轮图片')),
                ('name', models.CharField(max_length=50, verbose_name='图片名字')),
            ],
            options={
                'verbose_name_plural': '首页轮播推荐表',
                'db_table': 'tbl_recommend',
            },
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cg_name', models.CharField(max_length=20, verbose_name='小类名字')),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=False, to='shop.Category', verbose_name='所属大类')),
            ],
            options={
                'verbose_name_plural': '商品小类表',
                'db_table': 'tbl_sub_category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮件')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('chinese_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='中文名字')),
                ('phone_num', models.CharField(max_length=20, verbose_name='电话号码')),
                ('desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='个人描述')),
                ('user_img', models.ImageField(default='userimg/blank.png', max_length=200, upload_to=shop.models.upload_to)),
            ],
            options={
                'verbose_name_plural': '个人用户表',
                'db_table': 'tbl_user',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addressname', models.CharField(blank=True, max_length=20, null=True, verbose_name='地址名称')),
                ('receive_name', models.CharField(max_length=20, verbose_name='收货人名字')),
                ('receive_phone', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('address', models.TextField(max_length=200, verbose_name='收货地址')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='最新更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=False, to='shop.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '收货地址表',
                'db_table': 'tbl_address',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='prod_cg',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='shop.Sub_category', verbose_name='商品分类(小类)'),
        ),
        migrations.AddField(
            model_name='prod_collect',
            name='product',
            field=models.ForeignKey(on_delete=False, to='shop.Product', verbose_name='收藏的商品'),
        ),
        migrations.AddField(
            model_name='prod_collect',
            name='user',
            field=models.ForeignKey(on_delete=False, to='shop.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=False, to='shop.UserAddress', verbose_name='收货信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=False, to='shop.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=False, to='shop.Product', verbose_name='评论商品'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=False, to='shop.User', verbose_name='评论用户'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='shop.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=False, to='shop.Product', verbose_name='购物车产品'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=False, to='shop.User', verbose_name='用户'),
        ),
    ]
