# Generated by Django 2.1.5 on 2019-01-27 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img/%Y/%m/%d', verbose_name='首页滚轮图片')),
                ('name', models.CharField(max_length=50, verbose_name='图片名字')),
            ],
            options={
                'verbose_name_plural': '首页轮播推荐表',
                'db_table': 'tbl_recommend',
            },
        ),
        migrations.DeleteModel(
            name='Roller',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': '收货地址表'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': '购物车表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '商品大类表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '商品评论表'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '订单表'},
        ),
        migrations.AlterModelOptions(
            name='prod_collect',
            options={'verbose_name_plural': '产品收藏表'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '商品表'},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name_plural': '商品小类表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '个人用户表'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(max_length=200, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=200, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(upload_to='img/%Y/%m/%d', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_longname',
            field=models.TextField(max_length=100, verbose_name='商品长名字'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_rollimg1',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='商品轮播图'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_rollimg2',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='商品轮播图2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_rollimg3',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='商品轮播图3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_rollimg4',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='商品轮播图4'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='个人描述'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='userimg/blank.png', max_length=200, upload_to='img/%Y/%m/%d'),
        ),
    ]
