# Generated by Django 2.1.5 on 2019-01-30 16:21

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190127_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prod_num',
            field=models.IntegerField(default=1, verbose_name='已选商品数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(upload_to='%Y/%m/%d', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_rollimg1',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='商品轮播图'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_rollimg2',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='商品轮播图2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_rollimg3',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='商品轮播图3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_rollimg4',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='商品轮播图4'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='img',
            field=models.ImageField(upload_to=shop.models.upload_to, verbose_name='首页滚轮图片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='userimg/blank.png', max_length=200, upload_to='%Y/%m/%d'),
        ),
    ]
