# Generated by Django 2.1.5 on 2019-02-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addressname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='地址名称'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='shop.User', verbose_name='用户'),
        ),
    ]
